// Seleções: nome na Wikipédia (inglês) -> código, nome em português e "linhagem"
// (a mesma camisa através das Copas: Alemanha Ocidental e Alemanha são a mesma linhagem).
// cores: [principal, secundária] da camisa, para o escudo desenhado no jogo.
export const SELECOES = {
  "Algeria": { cod: "ALG", nome: "Argélia", cores: ["#FFFFFF", "#006233"] },
  "Angola": { cod: "ANG", nome: "Angola", cores: ["#CC092F", "#000000"] },
  "Argentina": { cod: "ARG", nome: "Argentina", cores: ["#75AADB", "#FFFFFF"] },
  "Australia": { cod: "AUS", nome: "Austrália", cores: ["#FFCD00", "#00843D"] },
  "Austria": { cod: "AUT", nome: "Áustria", cores: ["#FFFFFF", "#ED2939"] },
  "Belgium": { cod: "BEL", nome: "Bélgica", cores: ["#E30613", "#000000"] },
  "Bolivia": { cod: "BOL", nome: "Bolívia", cores: ["#007934", "#FFFFFF"] },
  "Bosnia and Herzegovina": { cod: "BIH", nome: "Bósnia", cores: ["#002395", "#FECB00"] },
  "Brazil": { cod: "BRA", nome: "Brasil", cores: ["#FEDD00", "#009C3B"] },
  "Bulgaria": { cod: "BUL", nome: "Bulgária", cores: ["#FFFFFF", "#00966E"] },
  "Cameroon": { cod: "CMR", nome: "Camarões", cores: ["#007A5E", "#CE1126"] },
  "Canada": { cod: "CAN", nome: "Canadá", cores: ["#D80621", "#FFFFFF"] },
  "Cape Verde": { cod: "CPV", nome: "Cabo Verde", cores: ["#003893", "#FFFFFF"] },
  "Chile": { cod: "CHI", nome: "Chile", cores: ["#D52B1E", "#0039A6"] },
  "China PR": { cod: "CHN", nome: "China", cores: ["#DE2910", "#FFDE00"] },
  "Colombia": { cod: "COL", nome: "Colômbia", cores: ["#FCD116", "#003893"] },
  "Costa Rica": { cod: "CRC", nome: "Costa Rica", cores: ["#CE1126", "#002B7F"] },
  "Croatia": { cod: "CRO", nome: "Croácia", cores: ["#FFFFFF", "#FF0000"] },
  "Curaçao": { cod: "CUW", nome: "Curaçao", cores: ["#002B7F", "#F9E814"] },
  "Czech Republic": { cod: "CZE", nome: "Tchéquia", cores: ["#D7141A", "#11457E"] },
  "Czechoslovakia": { cod: "TCH", nome: "Tchecoslováquia", cores: ["#D7141A", "#11457E"], extinta: true },
  "DR Congo": { cod: "COD", nome: "RD Congo", cores: ["#007FFF", "#CE1021"] },
  "Denmark": { cod: "DEN", nome: "Dinamarca", cores: ["#C60C30", "#FFFFFF"] },
  "East Germany": { cod: "GDR", nome: "Alemanha Oriental", cores: ["#0055A4", "#FFFFFF"], extinta: true },
  "Ecuador": { cod: "ECU", nome: "Equador", cores: ["#FFD100", "#034EA2"] },
  "Egypt": { cod: "EGY", nome: "Egito", cores: ["#CE1126", "#FFFFFF"] },
  "El Salvador": { cod: "SLV", nome: "El Salvador", cores: ["#0F47AF", "#FFFFFF"] },
  "England": { cod: "ENG", nome: "Inglaterra", cores: ["#FFFFFF", "#1E2B5C"] },
  "FR Yugoslavia": { cod: "YUG", nome: "Iugoslávia", linhagem: "YUG", cores: ["#0C4076", "#FFFFFF"], extinta: true },
  "France": { cod: "FRA", nome: "França", cores: ["#002654", "#FFFFFF"] },
  "Germany": { cod: "GER", nome: "Alemanha", linhagem: "GER", cores: ["#FFFFFF", "#000000"] },
  "Ghana": { cod: "GHA", nome: "Gana", cores: ["#FFFFFF", "#006B3F"] },
  "Greece": { cod: "GRE", nome: "Grécia", cores: ["#FFFFFF", "#0D5EAF"] },
  "Haiti": { cod: "HAI", nome: "Haiti", cores: ["#00209F", "#D21034"] },
  "Honduras": { cod: "HON", nome: "Honduras", cores: ["#FFFFFF", "#0073CF"] },
  "Hungary": { cod: "HUN", nome: "Hungria", cores: ["#CD2A3E", "#FFFFFF"] },
  "Iceland": { cod: "ISL", nome: "Islândia", cores: ["#02529C", "#FFFFFF"] },
  "Iran": { cod: "IRN", nome: "Irã", cores: ["#FFFFFF", "#239F40"] },
  "Iraq": { cod: "IRQ", nome: "Iraque", cores: ["#FFFFFF", "#007A3D"] },
  "Israel": { cod: "ISR", nome: "Israel", cores: ["#FFFFFF", "#0038B8"] },
  "Italy": { cod: "ITA", nome: "Itália", cores: ["#0066B3", "#FFFFFF"] },
  "Ivory Coast": { cod: "CIV", nome: "Costa do Marfim", cores: ["#FF8200", "#009A44"] },
  "Jamaica": { cod: "JAM", nome: "Jamaica", cores: ["#FED100", "#009B3A"] },
  "Japan": { cod: "JPN", nome: "Japão", cores: ["#0B2A6E", "#FFFFFF"] },
  "Jordan": { cod: "JOR", nome: "Jordânia", cores: ["#FFFFFF", "#CE1126"] },
  "Kuwait": { cod: "KUW", nome: "Kuwait", cores: ["#007A3D", "#FFFFFF"] },
  "Mexico": { cod: "MEX", nome: "México", cores: ["#006847", "#FFFFFF"] },
  "Morocco": { cod: "MAR", nome: "Marrocos", cores: ["#C1272D", "#006233"] },
  "Netherlands": { cod: "NED", nome: "Holanda", cores: ["#F36C21", "#FFFFFF"] },
  "New Zealand": { cod: "NZL", nome: "Nova Zelândia", cores: ["#FFFFFF", "#000000"] },
  "Nigeria": { cod: "NGA", nome: "Nigéria", cores: ["#008751", "#FFFFFF"] },
  "North Korea": { cod: "PRK", nome: "Coreia do Norte", cores: ["#ED1C27", "#FFFFFF"] },
  "Northern Ireland": { cod: "NIR", nome: "Irlanda do Norte", cores: ["#00843D", "#FFFFFF"] },
  "Norway": { cod: "NOR", nome: "Noruega", cores: ["#BA0C2F", "#FFFFFF"] },
  "Panama": { cod: "PAN", nome: "Panamá", cores: ["#DA121A", "#FFFFFF"] },
  "Paraguay": { cod: "PAR", nome: "Paraguai", cores: ["#D52B1E", "#FFFFFF"] },
  "Peru": { cod: "PER", nome: "Peru", cores: ["#FFFFFF", "#D91023"] },
  "Poland": { cod: "POL", nome: "Polônia", cores: ["#FFFFFF", "#DC143C"] },
  "Portugal": { cod: "POR", nome: "Portugal", cores: ["#C8102E", "#006600"] },
  "Qatar": { cod: "QAT", nome: "Catar", cores: ["#8A1538", "#FFFFFF"] },
  "Republic of Ireland": { cod: "IRL", nome: "Irlanda", cores: ["#169B62", "#FFFFFF"] },
  "Romania": { cod: "ROU", nome: "Romênia", cores: ["#FCD116", "#002B7F"] },
  "Russia": { cod: "RUS", nome: "Rússia", linhagem: "URS", cores: ["#FFFFFF", "#D52B1E"] },
  "Saudi Arabia": { cod: "KSA", nome: "Arábia Saudita", cores: ["#FFFFFF", "#006C35"] },
  "Scotland": { cod: "SCO", nome: "Escócia", cores: ["#1D2951", "#FFFFFF"] },
  "Senegal": { cod: "SEN", nome: "Senegal", cores: ["#FFFFFF", "#00853F"] },
  "Serbia": { cod: "SRB", nome: "Sérvia", linhagem: "YUG", cores: ["#C6363C", "#0C4076"] },
  "Serbia and Montenegro": { cod: "SCG", nome: "Sérvia e Montenegro", linhagem: "YUG", cores: ["#0C4076", "#FFFFFF"], extinta: true },
  "Slovakia": { cod: "SVK", nome: "Eslováquia", cores: ["#FFFFFF", "#0B4EA2"] },
  "Slovenia": { cod: "SVN", nome: "Eslovênia", cores: ["#FFFFFF", "#005DA4"] },
  "South Africa": { cod: "RSA", nome: "África do Sul", cores: ["#FFB612", "#007749"] },
  "South Korea": { cod: "KOR", nome: "Coreia do Sul", cores: ["#E4002B", "#FFFFFF"] },
  "Soviet Union": { cod: "URS", nome: "União Soviética", linhagem: "URS", cores: ["#CC0000", "#FFFFFF"], extinta: true },
  "Spain": { cod: "ESP", nome: "Espanha", cores: ["#C60B1E", "#FFC400"] },
  "Sweden": { cod: "SWE", nome: "Suécia", cores: ["#FECC02", "#006AA7"] },
  "Switzerland": { cod: "SUI", nome: "Suíça", cores: ["#D52B1E", "#FFFFFF"] },
  "Togo": { cod: "TOG", nome: "Togo", cores: ["#FFCE00", "#006A4E"] },
  "Trinidad and Tobago": { cod: "TRI", nome: "Trinidad e Tobago", cores: ["#DA1A35", "#000000"] },
  "Tunisia": { cod: "TUN", nome: "Tunísia", cores: ["#FFFFFF", "#E70013"] },
  "Turkey": { cod: "TUR", nome: "Turquia", cores: ["#E30A17", "#FFFFFF"] },
  "Ukraine": { cod: "UKR", nome: "Ucrânia", cores: ["#FFD500", "#005BBB"] },
  "United Arab Emirates": { cod: "UAE", nome: "Emirados Árabes", cores: ["#FFFFFF", "#00732F"] },
  "United States": { cod: "USA", nome: "Estados Unidos", cores: ["#FFFFFF", "#0A3161"] },
  "Uruguay": { cod: "URU", nome: "Uruguai", cores: ["#5CBFEB", "#000000"] },
  "Uzbekistan": { cod: "UZB", nome: "Uzbequistão", cores: ["#FFFFFF", "#1EB53A"] },
  "Wales": { cod: "WAL", nome: "País de Gales", cores: ["#C8102E", "#FFFFFF"] },
  "West Germany": { cod: "FRG", nome: "Alemanha Ocidental", linhagem: "GER", cores: ["#FFFFFF", "#000000"], extinta: true },
  "Yugoslavia": { cod: "YUG", nome: "Iugoslávia", linhagem: "YUG", cores: ["#0C4076", "#FFFFFF"], extinta: true },
  "Zaire": { cod: "ZAI", nome: "Zaire", linhagem: "COD", cores: ["#FFCE00", "#007A33"], extinta: true },
};
